import type {
  GoalDetail,
  GoalPeriodsResponse,
  GoalContributionsResponse,
} from '@activus/contracts';
export const goalId = '11111111-1111-4111-8111-111111111111';
export const fixedDetail: GoalDetail = {
  goal: {
    id: goalId,
    name: 'Walking distance',
    description: 'Walks recorded throughout the year.',
    activityKindId: goalId,
    activityVariantId: null,
    tagIds: [],
    targetType: 'measurement_total',
    targetValue: '500000',
    measurementDefinitionId: goalId,
    scheduleMode: 'fixed',
    recurrencePeriod: null,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isArchived: false,
    lifecycle: 'active',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  kindName: 'Walking',
  iconName: 'footprints',
  variantName: 'Outdoors',
  tagNames: ['With dog', 'Weekend'],
  measurementName: 'Distance',
  unitSymbol: 'km',
  displayCurrent: '540.125',
  displayTarget: '500',
  displayRemaining: '0',
  archivedReferences: [],
  defaultPeriod: null,
  progress: {
    scheduleMode: 'fixed',
    goalId,
    targetType: 'measurement_total',
    lifecycle: 'active',
    calculatedAt: '2026-09-10T00:00:00.000Z',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    currentValue: '540125',
    targetValue: '500000',
    remainingValue: '0',
    achieved: true,
  },
};
export const periodHistory: GoalPeriodsResponse = {
  nextBefore: '2026-08-30',
  items: [
    {
      startDate: '2026-09-07',
      endDate: '2026-09-13',
      calendarPeriodStart: '2026-09-07',
      calendarPeriodEnd: '2026-09-13',
      temporalState: 'current',
      currentValue: '2',
      targetValue: '3',
      remainingValue: '1',
      achieved: false,
      displayCurrent: '2',
      displayTarget: '3',
      displayRemaining: '1',
    },
    {
      startDate: '2026-08-31',
      endDate: '2026-09-06',
      calendarPeriodStart: '2026-08-31',
      calendarPeriodEnd: '2026-09-06',
      temporalState: 'ended',
      currentValue: '4',
      targetValue: '3',
      remainingValue: '0',
      achieved: true,
      displayCurrent: '4',
      displayTarget: '3',
      displayRemaining: '0',
    },
  ],
};
const current = periodHistory.items[0]!;
export const recurringDetail: GoalDetail = {
  ...fixedDetail,
  goal: {
    ...fixedDetail.goal,
    name: 'Three walks each week',
    targetType: 'activity_count',
    targetValue: '3',
    measurementDefinitionId: null,
    scheduleMode: 'recurring',
    recurrencePeriod: 'week',
  },
  measurementName: null,
  unitSymbol: null,
  displayCurrent: '2',
  displayTarget: '3',
  displayRemaining: '1',
  defaultPeriod: {
    startDate: current.startDate,
    endDate: current.endDate,
    calendarPeriodStart: current.calendarPeriodStart,
    calendarPeriodEnd: current.calendarPeriodEnd,
  },
  progress: {
    scheduleMode: 'recurring',
    goalId,
    targetType: 'activity_count',
    lifecycle: 'active',
    calculatedAt: '2026-09-10T00:00:00.000Z',
    currentPeriod: {
      startDate: current.startDate,
      endDate: current.endDate,
      calendarPeriodStart: current.calendarPeriodStart,
      calendarPeriodEnd: current.calendarPeriodEnd,
      currentValue: '2',
      targetValue: '3',
      remainingValue: '1',
      achieved: false,
      temporalState: 'current',
    },
    completedPeriods: 9,
    completedPeriodsAchieved: 6,
  },
};
export const contributions: GoalContributionsResponse = {
  startDate: '2026-09-07',
  endDate: '2026-09-13',
  pagination: { limit: 25, offset: 0, hasMore: true, nextOffset: 25 },
  items: [
    {
      activity: {
        id: goalId,
        activityDate: '2026-09-08',
        startedAt: null,
        name: 'A walk around the lake',
        durationSeconds: 3600,
        isPartial: false,
        hasNotes: false,
        kind: {
          id: goalId,
          name: 'Walking',
          iconName: 'footprints',
          color: '#67318F',
          isArchived: false,
        },
        variant: null,
        tags: [
          { id: goalId, name: 'With dog', color: '#67318F', isArchived: false },
        ],
        primaryMeasurement: null,
        fallback: { type: 'duration', durationSeconds: 3600 },
      },
      canonicalContribution: '2500.125',
      displayContribution: '2.500125',
    },
  ],
};
