import { z } from 'zod';

export const measurementUnitIds = [
  'metre',
  'kilometre',
  'mile',
  'foot',
  'second',
  'minute',
  'hour-minute',
  'kilogram',
  'pound',
  'count',
] as const;
export const MeasurementUnitIdSchema = z.enum(measurementUnitIds);
export const MeasurementUnitSchema = z.strictObject({
  id: MeasurementUnitIdSchema,
  label: z.string(),
  symbol: z.string(),
  dimension: z.enum(['length', 'duration', 'mass', 'count']),
  canonicalUnit: MeasurementUnitIdSchema,
  factorToCanonical: z.number().positive(),
  defaultPrecision: z.number().int().min(0).max(6),
  presentation: z.enum(['number', 'hours-minutes']),
});
export type MeasurementUnit = z.infer<typeof MeasurementUnitSchema>;
export const measurementUnits: readonly MeasurementUnit[] = [
  {
    id: 'metre',
    label: 'Metres',
    symbol: 'm',
    dimension: 'length',
    canonicalUnit: 'metre',
    factorToCanonical: 1,
    defaultPrecision: 0,
    presentation: 'number',
  },
  {
    id: 'kilometre',
    label: 'Kilometres',
    symbol: 'km',
    dimension: 'length',
    canonicalUnit: 'metre',
    factorToCanonical: 1000,
    defaultPrecision: 2,
    presentation: 'number',
  },
  {
    id: 'mile',
    label: 'Miles',
    symbol: 'mi',
    dimension: 'length',
    canonicalUnit: 'metre',
    factorToCanonical: 1609.344,
    defaultPrecision: 2,
    presentation: 'number',
  },
  {
    id: 'foot',
    label: 'Feet',
    symbol: 'ft',
    dimension: 'length',
    canonicalUnit: 'metre',
    factorToCanonical: 0.3048,
    defaultPrecision: 0,
    presentation: 'number',
  },
  {
    id: 'second',
    label: 'Seconds',
    symbol: 's',
    dimension: 'duration',
    canonicalUnit: 'second',
    factorToCanonical: 1,
    defaultPrecision: 0,
    presentation: 'number',
  },
  {
    id: 'minute',
    label: 'Minutes',
    symbol: 'min',
    dimension: 'duration',
    canonicalUnit: 'second',
    factorToCanonical: 60,
    defaultPrecision: 1,
    presentation: 'number',
  },
  {
    id: 'hour-minute',
    label: 'Hours and minutes',
    symbol: 'h / min',
    dimension: 'duration',
    canonicalUnit: 'second',
    factorToCanonical: 1,
    defaultPrecision: 0,
    presentation: 'hours-minutes',
  },
  {
    id: 'kilogram',
    label: 'Kilograms',
    symbol: 'kg',
    dimension: 'mass',
    canonicalUnit: 'kilogram',
    factorToCanonical: 1,
    defaultPrecision: 2,
    presentation: 'number',
  },
  {
    id: 'pound',
    label: 'Pounds',
    symbol: 'lb',
    dimension: 'mass',
    canonicalUnit: 'kilogram',
    factorToCanonical: 0.45359237,
    defaultPrecision: 2,
    presentation: 'number',
  },
  {
    id: 'count',
    label: 'Count',
    symbol: 'count',
    dimension: 'count',
    canonicalUnit: 'count',
    factorToCanonical: 1,
    defaultPrecision: 0,
    presentation: 'number',
  },
];
export const MeasurementUnitListResponseSchema = z.strictObject({
  items: z.array(MeasurementUnitSchema),
});
export type MeasurementUnitListResponse = z.infer<
  typeof MeasurementUnitListResponseSchema
>;
